from typing import Dict, Any

def generate_markdown_report(state: Dict[str, Any]) -> str:
    """
    Compiles the agent outputs from the state into a formatted Markdown report.
    
    Args:
        state (Dict[str, Any]): The current LangGraph AgentState.
        
    Returns:
        str: The Markdown formatted report.
    """
    report = []
    
    # Header
    report.append("# AI Resume Review & Career Guidance Report")
    report.append("Generated by the **AI Resume Reviewer Agent**")
    report.append("---")
    
    # 1. Executive Summary
    report.append("## 1. Executive Summary")
    report.append(f"**ATS Score**: `{state.get('ats_score', 0)}/100`\n")
    report.append(f"### Profile Summary")
    report.append(f"{state.get('summary', 'No summary generated.')}\n")
    
    # 2. ATS Analysis & Insights
    report.append("## 2. ATS Analysis & Insights")
    
    report.append("### Strengths")
    for strength in state.get('strengths', []):
        report.append(f"- {strength}")
    if not state.get('strengths'):
        report.append("- No strengths recorded.")
    report.append("")
    
    report.append("### Weaknesses & Areas of Improvement")
    for weakness in state.get('weaknesses', []):
        report.append(f"- {weakness}")
    if not state.get('weaknesses'):
        report.append("- No weaknesses recorded.")
    report.append("")

    report.append("### Weak Sections")
    for section in state.get('weak_sections', []):
        report.append(f"- {section}")
    if not state.get('weak_sections'):
        report.append("- All sections are well-structured.")
    report.append("")
    
    # 3. Skill & Keyword Analysis
    report.append("## 3. Skill & Keyword Analysis")
    
    report.append("### Extracted Skills")
    skills = ", ".join(state.get('extracted_skills', []))
    report.append(f"{skills if skills else 'None extracted.'}\n")
    
    report.append("### Missing / Recommended Skills")
    missing = ", ".join(state.get('missing_skills', []))
    report.append(f"{missing if missing else 'No missing skills identified.'}\n")
    
    # 4. Resume Bullet Point Improvements
    report.append("## 4. Resume Bullet Point Improvements")
    bullets = state.get('improved_bullets', [])
    if bullets:
        for idx, bullet in enumerate(bullets, 1):
            report.append(f"**Item {idx}:**")
            report.append(f"- *Original:* {bullet.get('original', '')}")
            report.append(f"- *Improved:* **{bullet.get('improved', '')}**")
            report.append(f"- *Why:* {bullet.get('reason', '')}")
            report.append("")
    else:
        report.append("No bullet points were identified for improvement.")
    report.append("")
    
    report.append("### Formatting Suggestions")
    for suggestion in state.get('formatting_suggestions', []):
        report.append(f"- {suggestion}")
    if not state.get('formatting_suggestions'):
        report.append("- Formatting appears correct.")
    report.append("")

    report.append("### Suggested Projects")
    for proj in state.get('project_suggestions', []):
        report.append(f"- {proj}")
    if not state.get('project_suggestions'):
        report.append("- No project suggestions provided.")
    report.append("")
    
    # 5. Interview Preparation
    report.append("## 5. Interview Preparation")
    
    # Helper for rendering questions
    def append_questions(section_title, questions_list):
        report.append(f"### {section_title}")
        if questions_list:
            for idx, q_dict in enumerate(questions_list, 1):
                report.append(f"{idx}. **Q: {q_dict.get('question', '')}**")
                report.append(f"   *Best Approach:* {q_dict.get('best_approach', '')}")
                report.append("")
        else:
            report.append("No questions generated for this section.\n")
            
    append_questions("HR & Behavioral Questions", state.get('hr_questions', []))
    append_questions("Java Questions", state.get('java_questions', []))
    append_questions("Data Structures & Algorithms (DSA) Questions", state.get('dsa_questions', []))
    append_questions("SQL Questions", state.get('sql_questions', []))
    append_questions("Project-Based Questions", state.get('project_questions', []))
    
    # 6. Career Guidance & Learning Roadmap
    report.append("## 6. Career Advisor Recommendations")
    
    report.append("### Recommended Certifications")
    certs = state.get('certifications', [])
    if certs:
        for cert in certs:
            report.append(f"- **{cert.get('name', '')}** (by {cert.get('provider', '')}): *{cert.get('relevance', '')}*")
    else:
        report.append("- No specific certifications recommended.")
    report.append("")
        
    report.append("### Missing Target Technologies")
    techs = state.get('missing_technologies', [])
    if techs:
        for tech in techs:
            report.append(f"- **{tech.get('name', '')}**: {tech.get('reason', '')}")
    else:
        report.append("- No missing technologies flagged.")
    report.append("")
    
    report.append("### Personalized Learning Roadmap")
    roadmap = state.get('learning_roadmap', [])
    if roadmap:
        for phase in roadmap:
            report.append(f"#### {phase.get('phase', '')}")
            report.append(f"- **Topics:** {', '.join(phase.get('topics', []))}")
            report.append(f"- **Resources:** {phase.get('resources', '')}")
            report.append("")
    else:
        report.append("- No roadmap steps generated.")
        
    return "\n".join(report)
